{{- if .Values.imageServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imageServer.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.imageServer.name }}
    {{- include "vista3d.labels" . | nindent 4 }}
spec:
  type: {{ .Values.imageServer.service.type }}
  ports:
    - port: {{ .Values.imageServer.service.port }}
      targetPort: {{ .Values.imageServer.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.imageServer.name }}
{{- end }}