{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.fullname" . }}-frontend
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "vista3d.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "vista3d.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            {{- /* Construct the URL for the fileserver dynamically */}}
            - name: IMAGE_SERVER
              value: "http://{{ .Values.imageServer.name }}-service:{{ .Values.imageServer.service.port }}"
            {{- /* These variables are now read from the values file */}}
            - name: OUTPUT_FOLDER
              value: {{ .Values.frontend.env.outputFolder | quote }}
            - name: DICOM_FOLDER
              value: {{ .Values.frontend.env.dicomFolder | quote }}
            - name: DOCKER_CONTAINER
              value: {{ .Values.frontend.env.dockerContainer | quote }}
            {{- if .Values.backend.enabled }}
            - name: VISTA3D_SERVER
              value: "http://{{ .Values.backend.name }}:{{ .Values.backend.service.port }}"
            {{- end }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.frontend.env.outputFolder }}
              subPath: {{ .Values.persistence.shared.outputSubPath }}
            - name: shared-data
              mountPath: {{ .Values.frontend.env.dicomFolder }}
              subPath: {{ .Values.persistence.shared.dicomSubPath }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.shared.existingClaim }}
{{- end }}